dist: trusty
language: c
sudo: required

compiler:
  - clang
  - gcc
  
before_install:
  - sudo apt-get update -qq
  - sudo apt install libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-image-dev libsdl2-ttf-dev

# Build steps
script:
  - make
  - make test
  - make install
  - make run
  - make ctest
  - make clean
  - mkdir build && cd build
  - cmake ..
  - make
